const $ = s => document.querySelector(s);
const views = document.querySelectorAll('.view');
let sets = JSON.parse(localStorage.getItem('tim-tu-vung-sets') || '[]');
let currentSet = null, session = null;
const save = () => localStorage.setItem('tim-tu-vung-sets', JSON.stringify(sets));
const show = name => { views.forEach(v=>v.classList.remove('active')); $('#'+name+'View').classList.add('active'); window.scrollTo(0,0); };
const toast = msg => { const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200); };
const days = date => Math.ceil((new Date(date)-new Date())/86400000);
function renderHome(){ const grid=$('#setsGrid'), empty=$('#emptyState'); grid.innerHTML=''; $('#setCount').textContent=sets.length?`${sets.length} bộ từ`:''; empty.style.display=sets.length?'none':'block'; sets.forEach(set=>{const available=set.words.filter(w=>!w.hiddenUntil||new Date(w.hiddenUntil)<=new Date()).length;const card=document.createElement('button');card.className='set-card';card.innerHTML=`<span class="set-icon">☷</span><h3>${esc(set.name)}</h3><p>${set.words.length} từ vựng</p><span class="available">${available} từ sẵn sàng ôn →</span>`;card.onclick=()=>openDetail(set.id);grid.appendChild(card);}); }
function esc(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
function makeRow(word='',meaning=''){const row=document.createElement('div');row.className='word-row';row.innerHTML=`<input class="word" placeholder="Từ vựng (English / 中文)" value="${esc(word)}"><input class="meaning" placeholder="Ý nghĩa tiếng Việt" value="${esc(meaning)}"><button class="remove" title="Xóa">×</button>`;row.querySelector('.remove').onclick=()=>{if(document.querySelectorAll('.word-row').length>1)row.remove();else toast('Bộ từ cần ít nhất một hàng.');};$('#wordRows').appendChild(row)}
function openEditor(id){currentSet=id?sets.find(s=>s.id===id):null;$('#editorHeading').textContent=currentSet?'Chỉnh sửa bộ từ':'Bộ từ của mình';$('#setName').value=currentSet?.name||'';$('#wordRows').innerHTML='';(currentSet?.words||[{word:'',meaning:''}]).forEach(w=>makeRow(w.word,w.meaning));show('editor')}
function saveEditor(){const name=$('#setName').value.trim();const words=[...document.querySelectorAll('.word-row')].map(r=>({word:r.querySelector('.word').value.trim(),meaning:r.querySelector('.meaning').value.trim(),hiddenUntil:null})).filter(w=>w.word&&w.meaning);if(!name)return toast('Hãy đặt tên cho bộ từ.');if(!words.length)return toast('Hãy thêm ít nhất một cặp từ và nghĩa.');if(currentSet){const old=sets.find(s=>s.id===currentSet.id);old.name=name;old.words=words.map((w,i)=>({...w,hiddenUntil:old.words[i]?.hiddenUntil||null}));currentSet=old}else{currentSet={id:crypto.randomUUID(),name,words};sets.unshift(currentSet)}save();openDetail(currentSet.id);toast('Đã lưu bộ từ.');}
function openDetail(id){currentSet=sets.find(s=>s.id===id);$('#detailName').textContent=currentSet.name;const avail=currentSet.words.filter(w=>!w.hiddenUntil||new Date(w.hiddenUntil)<=new Date()).length;$('#detailMeta').textContent=`${currentSet.words.length} từ · ${avail} từ đang sẵn sàng ôn`;$('#wordList').innerHTML=currentSet.words.map(w=>`<div class="word-item"><strong>${esc(w.word)}</strong><span>${esc(w.meaning)}</span>${w.hiddenUntil&&new Date(w.hiddenUntil)>new Date()?`<small class="hidden-tag">ẩn ${days(w.hiddenUntil)} ngày</small>`:''}</div>`).join('');show('detail')}
function begin(mode, override){const pool=override||currentSet.words.filter(w=>!w.hiddenUntil||new Date(w.hiddenUntil)<=new Date());if(!pool.length)return toast('Các từ đều đang được ẩn. Hãy quay lại sau nhé.');session={mode,queue:[...pool],index:0,wrong:[],correct:0};show('study');renderQuestion();}
function renderQuestion(){const w=session.queue[session.index];const meaning=session.mode==='meaning';$('#studyPrompt').textContent=meaning?'NHÌN TỪ VỰNG · VIẾT NGHĨA':'NHÌN Ý NGHĨA · VIẾT TỪ VỰNG';$('#question').textContent=meaning?w.word:w.meaning;$('#answerLabel').textContent=meaning?'Ý nghĩa của từ này là':'Từ vựng tương ứng là';$('#answerInput').value='';$('#feedback').className='feedback';$('#answerInput').focus();const pct=Math.round(session.index/session.queue.length*100);$('#progressText').textContent=`Từ ${session.index+1} / ${session.queue.length}`;$('#progressBar').style.width=pct+'%';}
function normalize(s){return s.toLocaleLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\p{L}\p{N}\s]/gu,' ').replace(/\s+/g,' ').trim()}
function similarity(a,b){a=normalize(a);b=normalize(b);if(a===b)return 100;const aa=new Set(a.split(' ').filter(Boolean)),bb=new Set(b.split(' ').filter(Boolean));const common=[...aa].filter(x=>bb.has(x)).length;const j=common/Math.max(aa.size,bb.size);let d=Array.from({length:a.length+1},(_,i)=>[i]);for(let j2=1;j2<=b.length;j2++){d[0][j2]=j2;for(let i=1;i<=a.length;i++)d[i][j2]=a[i-1]===b[j2-1]?d[i-1][j2-1]:1+Math.min(d[i-1][j2],d[i][j2-1],d[i-1][j2-1]);}const lev=1-d[a.length][b.length]/Math.max(a.length,b.length,1);return Math.round((j*.6+lev*.4)*100)}
function check(){const answer=$('#answerInput').value.trim();if(!answer)return toast('Hãy nhập câu trả lời trước.');const w=session.queue[session.index];const score=session.mode==='meaning'?similarity(answer,w.meaning):(normalize(answer)===normalize(w.word)?100:0);const ok=session.mode==='meaning'?score>=70:score===100;const f=$('#feedback');f.className='feedback show '+(ok?'good':'bad');f.innerHTML=ok?`<b>${session.mode==='meaning'?`Tốt lắm! Độ tương đồng: ${score}%`:'Chính xác 100%!'}</b>Đáp án gốc: ${esc(session.mode==='meaning'?w.meaning:w.word)}`:`<b>${session.mode==='meaning'?`Độ tương đồng: ${score}%`:'Chưa chính xác.'}</b>Đáp án gốc: ${esc(session.mode==='meaning'?w.meaning:w.word)}`;$('#checkBtn').textContent='Tiếp tục →';$('#checkBtn').onclick=()=>next(ok,w);}
function next(ok,w){if(ok)session.correct++;else session.wrong.push(w);session.index++;$('#checkBtn').innerHTML='Kiểm tra <span>↵</span>';$('#checkBtn').onclick=check;if(session.index>=session.queue.length)return finish();renderQuestion();}
function finish(){const n=session.wrong.length;$('#completeTitle').textContent=n?'Bạn đã hoàn thành lượt ôn!':'Xuất sắc, hoàn hảo!';$('#completeText').textContent=n?`Bạn trả lời đúng ${session.correct}/${session.queue.length} từ. Có ${n} từ cần ôn lại ngay bây giờ.`:`Bạn đã trả lời đúng toàn bộ ${session.queue.length} từ trong lượt này.`;$('#retryBtn').style.display=n?'inline-block':'none';show('complete');}
function skip(){const w=session.queue[session.index];const source=currentSet.words.find(x=>x.word===w.word&&x.meaning===w.meaning);source.hiddenUntil=new Date(Date.now()+3*86400000).toISOString();save();toast('Đã ẩn từ này trong 3 ngày.');session.queue.splice(session.index,1);if(!session.queue.length)return finish();if(session.index>=session.queue.length)session.index=0;renderQuestion();}
$('#newSetBtn').onclick=()=>openEditor();$('#homeBtn').onclick=()=>{renderHome();show('home')};$('#addRowBtn').onclick=()=>makeRow();$('#saveSetBtn').onclick=saveEditor;$('#editBtn').onclick=()=>openEditor(currentSet.id);$('#startBtn').onclick=()=>show('mode');document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>{if(x.dataset.go==='home'){renderHome();show('home')}else if(x.dataset.go==='detail')openDetail(currentSet.id)});document.querySelectorAll('.mode-card').forEach(x=>x.onclick=()=>begin(x.dataset.mode));$('#checkBtn').onclick=check;$('#skipBtn').onclick=skip;$('#exitStudy').onclick=()=>openDetail(currentSet.id);$('#retryBtn').onclick=()=>begin(session.mode,session.wrong);$('#answerInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('#checkBtn').click()});
if(!sets.length){sets=[{id:'demo',name:'Tiếng Trung · Mẫu cơ bản',words:[{word:'你好',meaning:'xin chào',hiddenUntil:null},{word:'谢谢',meaning:'cảm ơn',hiddenUntil:null},{word:'学习',meaning:'học tập',hiddenUntil:null}]}];save();}renderHome();
